Repository allthings/elements, pull requests merged in 2018-08, with the labels that each got.

#312 Typeahead downshift
  .eslintrc
  doc/reference/atoms/Spinner.md
  doc/reference/organisms/Typeahead.md
  package.json
  src/atoms/Input.jsx
  src/atoms/Spinner.jsx
  src/atoms/__snapshots__/Input.test.jsx.snap
  src/behaviour/__snapshots__/FormValidityProvider.test.jsx.snap
  src/index.js
  src/molecules/__snapshots__/TextInput.test.js.snap
  src/organisms/Typeahead.jsx
  src/organisms/Typeahead.test.jsx
  src/organisms/__snapshots__/Typeahead.test.jsx.snap
  src/utils/escapeRegex.js
  stories/TypeaheadStory.jsx
  stories/data/movies.json
  stories/data/names.json
  stories/index.js
  yarn.lock
Labels: new component

#350 Add new behavior when using the clear icon ❎.
  src/organisms/Typeahead.jsx
  src/organisms/Typeahead.test.jsx
Labels: enhancement

#353 Fix for the clear icon.
  src/organisms/Typeahead.jsx
  src/organisms/Typeahead.test.jsx
Labels: bug

#354 Don't show the clear icon in cleared controlled component.
  src/organisms/Typeahead.jsx
  src/organisms/Typeahead.test.jsx
Labels: bug
